/**
 * All study destinations. Order: first 8 are shown on home row and in navbar (your sequence).
 * image: paths match files in public/destinations/ (e.g. UK.webp, new_zealand.webp).
 * flagIcon: used in navbar and on destinations page.
 * longDescription & highlights: used on destination detail page.
 */
export type Destination = {
  id: number;
  name: string;
  flagIcon: string;
  image: string;
  link: string;
  description: string;
  tag: string;
  longDescription: string;
  highlights: string[];
};

export const destinations: Destination[] = [
  { id: 1, name: "UK", flagIcon: "https://flagcdn.com/w40/gb.png", image: "/destinations/UK.webp", link: "/education/destinations/uk", description: "World-class universities, short courses, and strong post-study work options.", tag: "World-class rankings", longDescription: "The United Kingdom is home to some of the world's most prestigious universities, including Oxford, Cambridge, and institutions across London, Edinburgh, and Manchester. UK degrees are recognised globally and often completed in three years for undergraduates, with one-year master's programmes widely available. The Graduate Route allows international students to stay and work for two years (or three for PhD graduates) after completing their degree. From business and law to engineering and the arts, UK institutions offer a huge range of courses taught in English, with strong links to industry and research.", highlights: ["Short, intensive degrees (e.g. 3-year BA, 1-year MSc)", "Graduate Route: 2–3 years post-study work", "Globally recognised qualifications", "Diverse cities and strong student support"] },
  { id: 2, name: "New Zealand", flagIcon: "https://flagcdn.com/w40/nz.png", image: "/destinations/new_zealand.webp", link: "/education/destinations/new-zealand", description: "Small class sizes, practical learning, and a safe, friendly environment.", tag: "Safe & friendly", longDescription: "New Zealand offers a high quality of life, stunning landscapes, and universities that rank among the world's best. Class sizes are typically smaller than in larger countries, so you get more direct contact with lecturers and a practical, hands-on approach to learning. International students can work part-time during term and full-time in holidays, and may be eligible for post-study work rights. New Zealand is known for its welcoming culture, safety, and focus on work–life balance, making it an attractive choice for students who want both a strong education and a great lifestyle.", highlights: ["Small class sizes and practical learning", "Post-study work and part-time work options", "Safe, welcoming, English-speaking environment", "Strong in agriculture, tourism, and tech"] },
  { id: 3, name: "France", flagIcon: "https://flagcdn.com/w40/fr.png", image: "/destinations/France.webp", link: "/education/destinations/france", description: "Prestigious grandes écoles, arts, and innovation in the heart of Europe.", tag: "Culture & excellence", longDescription: "France combines world-famous culture with top-tier education. Grandes écoles and universities offer programmes in business, engineering, arts, and humanities, with a growing number of courses taught in English. Tuition at public universities remains relatively low for EU and international students, and major cities like Paris, Lyon, and Toulouse are hubs for innovation and research. Studying in France means access to the wider EU job market, rich cultural life, and a high quality of life.", highlights: ["Grandes écoles and renowned universities", "Affordable public university tuition", "Many English-taught programmes", "EU access and vibrant student cities"] },
  { id: 4, name: "Spain", flagIcon: "https://flagcdn.com/w40/es.png", image: "/destinations/Spain.webp", link: "/education/destinations/spain", description: "Vibrant student life, affordable tuition, and Spanish language programmes.", tag: "Sun & study", longDescription: "Spain offers vibrant cities, a warm climate, and universities that attract students from across Europe and the world. Tuition fees are generally affordable, and living costs in many cities are lower than in northern Europe. You can study in Spanish or choose from a growing number of English-taught degrees in business, engineering, and tourism. From Barcelona and Madrid to Valencia and Seville, Spain combines strong academic options with a relaxed, social student lifestyle.", highlights: ["Affordable tuition and cost of living", "Spanish and English-taught programmes", "Vibrant student life and culture", "EU member with Schengen access"] },
  { id: 5, name: "Australia", flagIcon: "https://flagcdn.com/w40/au.png", image: "/destinations/Australia.webp", link: "/education/destinations/australia", description: "Leading universities, relaxed lifestyle, and post-study work rights.", tag: "Work rights", longDescription: "Australia is a top choice for international students seeking high-ranked universities, a relaxed lifestyle, and clear post-study work pathways. Institutions in Sydney, Melbourne, Brisbane, and Perth offer a wide range of programmes, with strong emphasis on research and employability. The Temporary Graduate visa allows eligible graduates to stay and work for two to six years depending on qualification level. Australia's diverse society, outdoor lifestyle, and English-speaking environment make it easy to settle in.", highlights: ["Post-study work visa (2–6 years depending on level)", "Top-ranked universities and research", "English-speaking, multicultural society", "Strong employment and quality of life"] },
  { id: 6, name: "Ireland", flagIcon: "https://flagcdn.com/w40/ie.png", image: "/destinations/Ireland.webp", link: "/education/destinations/ireland", description: "English-speaking EU hub with strong tech and pharma links.", tag: "EU gateway", longDescription: "Ireland is the only English-speaking country in the eurozone and a major hub for tech, pharma, and finance. Universities in Dublin, Cork, and Galway offer internationally recognised degrees and close ties to global companies with European HQs in Ireland. Graduates can access the Irish and wider EU job market, and the Third Level Graduate Scheme allows non-EU students to stay and seek employment after finishing their studies. Friendly, safe, and well connected, Ireland is ideal for students who want an English-language education with a strong EU career angle.", highlights: ["English-speaking EU member", "Tech, pharma, and finance hub", "Graduate scheme for post-study stay", "Globally recognised universities"] },
  { id: 7, name: "Sweden", flagIcon: "https://flagcdn.com/w40/se.png", image: "/destinations/Sweden.webp", link: "/education/destinations/sweden", description: "Innovation, sustainability, and many English-taught programmes.", tag: "Innovation", longDescription: "Sweden is known for innovation, sustainability, and a high standard of living. Universities in Stockholm, Lund, Uppsala, and Gothenburg offer hundreds of English-taught master's programmes and a collaborative, research-driven approach to learning. Although tuition applies for non-EU students, scholarships are available, and the quality of education and quality of life are consistently ranked among the world's best. Sweden's strong focus on equality, design, and technology makes it a great fit for students in engineering, business, and the sciences.", highlights: ["Many English-taught master's programmes", "Innovation and sustainability focus", "High quality of life and equality", "Strong research and industry links"] },
  { id: 8, name: "Malta", flagIcon: "https://flagcdn.com/w40/mt.png", image: "/destinations/Malta.webp", link: "/education/destinations/malta", description: "Sun, sea, and English-medium education in the Mediterranean.", tag: "Mediterranean", longDescription: "Malta offers English-medium education in a sunny, safe EU country with a rich history and a growing number of international students. The University of Malta and private institutions provide degrees in business, hospitality, and other fields, often at competitive fees. As an EU member, Malta allows free movement and work rights across the bloc. Small size, year-round sunshine, and a relaxed Mediterranean lifestyle make Malta an attractive option for students who want an English-language degree in a compact, friendly environment.", highlights: ["English-medium education in the EU", "Sunny, safe, Mediterranean lifestyle", "Competitive fees and EU work rights", "Growing international student community"] },
  { id: 9, name: "Cyprus", flagIcon: "https://flagcdn.com/w40/cy.png", image: "/destinations/Cyprus.webp", link: "/education/destinations/cyprus", description: "Affordable EU degrees and a growing international student community.", tag: "Affordable EU", longDescription: "Cyprus combines EU membership with affordable tuition and living costs and a warm, welcoming environment. Universities in Nicosia, Limassol, and other cities offer programmes in business, health, engineering, and more, many in English. International students benefit from EU recognition of degrees and the chance to live in a safe, Mediterranean country. Cyprus is increasingly popular with students looking for value, sunshine, and an English-taught EU degree.", highlights: ["Affordable tuition and cost of living", "EU-recognised degrees, many in English", "Safe, sunny, Mediterranean setting", "Growing international student base"] },
  { id: 10, name: "Dubai", flagIcon: "https://flagcdn.com/w40/ae.png", image: "/destinations/Dubai.webp", link: "/education/destinations/dubai", description: "Global hub with branch campuses and business-focused programmes.", tag: "Global hub", longDescription: "Dubai has become a major education hub, hosting branch campuses of universities from the UK, Australia, and elsewhere. Programmes in business, engineering, and hospitality are tailored to a global, career-focused audience, and the city's tax-free environment and strategic location attract students and professionals from around the world. Studying in Dubai can open doors to internships and jobs in the UAE and the wider Gulf region, with a modern, multicultural lifestyle.", highlights: ["Branch campuses of international universities", "Business, engineering, and hospitality focus", "Global city with strong job market", "Tax-free, multicultural environment"] },
  { id: 11, name: "USA", flagIcon: "https://flagcdn.com/w40/us.png", image: "/destinations/USA.webp", link: "/education/destinations/usa", description: "The world's largest higher education system and top research.", tag: "Top research", longDescription: "The United States has the world's largest and most diverse higher education system, with thousands of colleges and universities offering every imaginable field of study. From Ivy League and top public research universities to liberal arts colleges and specialised schools, the USA leads in research, innovation, and global rankings. Flexible degree structures, generous funding and scholarship options, and strong career services make it a prime destination for ambitious students. Post-study work options (e.g. OPT) allow graduates to gain experience in the US job market.", highlights: ["Largest and most diverse higher education system", "World-leading research and rankings", "Flexible degrees and scholarship opportunities", "OPT and other post-study work options"] },
  { id: 12, name: "Denmark", flagIcon: "https://flagcdn.com/w40/dk.png", image: "/destinations/Denmark.webp", link: "/education/destinations/denmark", description: "Quality of life, design, and English-taught degrees.", tag: "Quality of life", longDescription: "Denmark consistently ranks among the best countries for quality of life, happiness, and education. Universities in Copenhagen, Aarhus, and elsewhere offer many English-taught programmes in design, engineering, sustainability, and business. Teaching style is often collaborative and project-based. Although tuition applies for non-EU/EEA students, scholarships exist, and the high standard of living and strong welfare system make Denmark an attractive long-term base for study and career.", highlights: ["High quality of life and happiness rankings", "English-taught programmes in design and more", "Collaborative, project-based learning", "Strong welfare and work–life balance"] },
  { id: 13, name: "Italy", flagIcon: "https://flagcdn.com/w40/it.png", image: "/destinations/Italy.webp", link: "/education/destinations/italy", description: "Art, architecture, and historic universities across the country.", tag: "Art & history", longDescription: "Italy is home to some of the world's oldest universities and unrivalled heritage in art, architecture, design, and engineering. From Milan and Rome to Florence, Bologna, and Turin, institutions offer programmes in Italian and a growing number in English. Tuition at public universities is often relatively low, and living in Italy means access to EU mobility and a unique cultural and lifestyle experience. Ideal for students of design, arts, humanities, and engineering.", highlights: ["Historic universities and arts heritage", "Affordable public university tuition", "Growing English-taught offer", "EU member with rich culture and lifestyle"] },
  { id: 14, name: "Hungary", flagIcon: "https://flagcdn.com/w40/hu.png", image: "/destinations/Hungary.webp", link: "/education/destinations/hungary", description: "Affordable EU study, medicine and engineering in English.", tag: "Affordable EU", longDescription: "Hungary offers affordable tuition and living costs within the EU, with a strong tradition in medicine, dentistry, engineering, and business. Budapest and other cities host universities that teach in English and attract thousands of international students each year. Degrees are EU-recognised, and the central European location makes travel and cultural exchange easy. Hungary is a practical choice for students seeking quality, value, and an English-medium degree in the heart of Europe.", highlights: ["Affordable tuition and cost of living", "Strong medicine, dentistry, and engineering in English", "EU-recognised degrees", "Central European location and culture"] },
  { id: 15, name: "Turkey", flagIcon: "https://flagcdn.com/w40/tr.png", image: "/destinations/Turkey.webp", link: "/education/destinations/turkey", description: "Bridge between Europe and Asia with growing international programmes.", tag: "Crossroads", longDescription: "Turkey sits at the crossroads of Europe and Asia and has invested heavily in higher education and internationalisation. Universities in Istanbul, Ankara, and Izmir offer a growing number of programmes in English in fields such as business, engineering, and international relations. Tuition and living costs are often lower than in Western Europe, and the country's rich history, culture, and strategic position make it an interesting option for students seeking an international experience and career links to both Europe and the wider region.", highlights: ["Growing English-taught programmes", "Strategic location between Europe and Asia", "Affordable costs and rich culture", "Strong focus on internationalisation"] },
  { id: 16, name: "Canada", flagIcon: "https://flagcdn.com/w40/ca.png", image: "/destinations/Canada.webp", link: "/education/destinations/canada", description: "Safe, welcoming, with quality education and immigration pathways.", tag: "Pathway to PR", longDescription: "Canada is known for safety, diversity, and high-quality education with clear pathways to work and permanent residence. Universities and colleges across Toronto, Vancouver, Montreal, and other cities offer a wide range of programmes, and the Post-Graduation Work Permit allows eligible graduates to gain Canadian work experience. Many international students use their study and work experience as a step toward permanent residence. Canada's welcoming policies and multicultural society make it one of the most popular study destinations globally.", highlights: ["Pathways to work and permanent residence", "Post-Graduation Work Permit for graduates", "Safe, diverse, high-quality education", "Strong universities and colleges nationwide"] },
  { id: 17, name: "Finland", flagIcon: "https://flagcdn.com/w40/fi.png", image: "/destinations/Finland.webp", link: "/education/destinations/finland", description: "World-leading education system and innovation.", tag: "Education leader", longDescription: "Finland is renowned for its education system, innovation, and quality of life. Universities and universities of applied sciences offer programmes in English in technology, design, business, and environmental sciences. Although tuition applies for non-EU students, scholarships are available, and the teaching approach is practical and collaborative. Finland's focus on equality, sustainability, and research makes it a strong choice for students interested in tech, design, and applied sciences.", highlights: ["World-leading education and innovation", "English-taught programmes in tech and design", "Scholarships for international students", "High quality of life and equality"] },
  { id: 18, name: "Germany", flagIcon: "https://flagcdn.com/w40/de.png", image: "/destinations/Germany.webp", link: "/education/destinations/germany", description: "Low or no tuition fees and strong engineering and research.", tag: "Tuition-free options", longDescription: "Germany is one of the most popular study destinations in Europe, offering low or no tuition fees at public universities for domestic and international students alike. Institutions in Berlin, Munich, Hamburg, and across the country are leaders in engineering, natural sciences, and research. A growing number of programmes are taught in English, especially at master's level. Strong economy, central EU location, and post-study work options make Germany an excellent choice for career-focused students.", highlights: ["Low or no tuition at public universities", "Top engineering and research", "Many English-taught programmes", "Strong economy and EU job market access"] },
  { id: 19, name: "Lithuania", flagIcon: "https://flagcdn.com/w40/lt.png", image: "/destinations/Lithuania.webp", link: "/education/destinations/lithuania", description: "Affordable EU study and a growing English-taught offer.", tag: "Affordable EU", longDescription: "Lithuania offers affordable EU education with a growing number of English-taught programmes in Vilnius, Kaunas, and other cities. Tuition and living costs are among the lowest in the EU, while degrees are fully recognised across the bloc. Fields such as business, IT, and health are well represented. Lithuania is a practical choice for students who want an EU degree, modern facilities, and a safe, compact country with easy access to the rest of Europe.", highlights: ["Affordable tuition and living in the EU", "Growing English-taught programmes", "EU-recognised degrees", "Safe, modern, well-connected"] },
  { id: 20, name: "Malaysia", flagIcon: "https://flagcdn.com/w40/my.png", image: "/destinations/Malaysia.webp", link: "/education/destinations/malaysia", description: "Rising hub with twinning programmes and lower costs.", tag: "Value & growth", longDescription: "Malaysia has emerged as a popular study destination in Asia, offering twinning and branch campus programmes with UK and Australian universities at a fraction of the cost of studying in those countries. Kuala Lumpur and other cities host a mix of local and international institutions in business, engineering, and hospitality. English is widely used in higher education. Malaysia appeals to students who want internationally recognised qualifications, a multicultural environment, and lower tuition and living costs.", highlights: ["Twinning and branch campuses (UK, Australian partners)", "Lower tuition and living costs", "English-medium education", "Multicultural and growing hub"] },
];

/** Get destination by URL slug (e.g. "uk" -> UK, "new-zealand" -> New Zealand). */
export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.link === `/education/destinations/${slug}`);
}

/** All destination slugs for sitemap etc. */
export function getAllDestinationSlugs(): string[] {
  return destinations.map((d) => d.link.replace(/^\/education\/destinations\//, ""));
}

/** First 8 destinations: shown on home row carousel. */
export const popularDestinations = destinations.slice(0, 8);

/** First 7 destinations: shown in navbar dropdown (2 per row). */
export const navbarDestinations = destinations.slice(0, 7);
