/**
 * Partner universities – unique list. Optional logoDomain used for Clearbit logo (https://logo.clearbit.com/{domain}).
 * Leave logoDomain empty to show initials only.
 */
export const partnerUniversities = [
  { name: "Ulster University", logoDomain: "ulster.ac.uk" },
  { name: "Teesside University", logoDomain: "tees.ac.uk" },
  { name: "Bangor University", logoDomain: "bangor.ac.uk" },
  { name: "GBS Global Applied Knowledge", logoDomain: "" },
  { name: "Capilano University", logoDomain: "capilanou.ca" },
  { name: "Herzing University", logoDomain: "herzing.edu" },
  { name: "Bahçeşehir University", logoDomain: "bau.edu.tr" },
  { name: "IBAT College Dublin", logoDomain: "ibat.ie" },
  { name: "Southampton Solent University", logoDomain: "solent.ac.uk" },
  { name: "QA Partnership", logoDomain: "qa.com" },
  { name: "University of Northampton", logoDomain: "northampton.ac.uk" },
  { name: "Leeds Trinity University", logoDomain: "leedstrinity.ac.uk" },
  { name: "Abertay University", logoDomain: "abertay.ac.uk" },
  { name: "University of Europe for Applied Sciences", logoDomain: "university-europe.de" },
  { name: "University of Niagara Falls Canada", logoDomain: "unfc.ca" },
  { name: "Webster University", logoDomain: "webster.edu" },
  { name: "Beykoz University", logoDomain: "beykoz.edu.tr" },
  { name: "College de Paris", logoDomain: "collegedeparis.fr" },
  { name: "The University of Law", logoDomain: "law.ac.uk" },
  { name: "Anglia Ruskin University", logoDomain: "aru.ac.uk" },
  { name: "Heriot-Watt University", logoDomain: "hw.ac.uk" },
  { name: "Gisma University of Applied Sciences", logoDomain: "gisma.com" },
  { name: "Fanshawe College", logoDomain: "fanshawec.ca" },
  { name: "Southern Cross Institute", logoDomain: "" },
  { name: "Halic University", logoDomain: "halic.edu.tr" },
  { name: "De Montfort University Dubai", logoDomain: "dmu.ac.uk" },
  { name: "Canterbury Christ Church University", logoDomain: "canterbury.ac.uk" },
  { name: "Hartpury University", logoDomain: "hartpury.ac.uk" },
  { name: "University for the Creative Arts", logoDomain: "uca.ac.uk" },
  { name: "Berlin School of Business & Innovation", logoDomain: "bsbi.edu" },
  { name: "Concordia University", logoDomain: "concordia.ca" },
  { name: "Avila University", logoDomain: "avila.edu" },
  { name: "Skills Australia Institute", logoDomain: "" },
  { name: "University of Applied Sciences Europe", logoDomain: "university-europe.de" },
  { name: "GUS Medical & Veterinary Schools", logoDomain: "" },
  { name: "University of Gloucestershire", logoDomain: "glos.ac.uk" },
  { name: "Eton College", logoDomain: "etoncollege.com" },
  { name: "University of South Wales", logoDomain: "southwales.ac.uk" },
  { name: "Arden University Berlin", logoDomain: "arden.ac.uk" },
  { name: "University Canada West", logoDomain: "ucanwest.ca" },
  { name: "LIM College", logoDomain: "limcollege.edu" },
  { name: "Kadir Has University", logoDomain: "khas.edu.tr" },
  { name: "IC University of Applied Sciences", logoDomain: "" },
] as const;
